feat: Добавлен компонент ClickAwayListener
quarx-ui/quarx pull request #100
Opened 2022-10-29 22:17 UTC by maximzadorkin

resolve #38

2022-10-31 09:30 UTC, aak-lear requested changes

2022-10-31 11:04 UTC, maximzadorkin commented on packages/core/src/unstyled/ClickAwayListener/types.ts
> +     * Данное свойство изменяет обработку поральных элементов.
портальных :D

2022-10-31 11:16 UTC, maximzadorkin commented on packages/core/package.json
> +    "path-composedpath-polyfill": "0.0.1"
Это ты про полифилл?

2022-10-31 12:31 UTC, aak-lear commented on packages/core/package.json
> +    "path-composedpath-polyfill": "0.0.1"
да

2022-11-02 06:02 UTC, ISAYwtf commented on packages/core/src/index.ts
> +export * from './unstyled/ClickAwayListener';
этот экспорт оказался не в своей стае)

2022-11-02 06:06 UTC, ISAYwtf approved these changes

2022-11-02 07:35 UTC, aak-lear approved these changes

2022-11-03 15:10 UTC, maximzadorkin commented
Ready to merge)

2022-11-09 12:35 UTC, popopolyakov commented on packages/core/src/unstyled/ClickAwayListener/ClickAwayListener.tsx
> +    React.useEffect(() => {
```suggestion
    useEffect(() => {
```

2022-11-09 12:36 UTC, popopolyakov commented on packages/core/src/unstyled/ClickAwayListener/ClickAwayListener.tsx
> +    }) as EventListener;
если убрать каст, вроде бы особо ругаться не будет, может стоит убрать?

2022-11-14 06:58 UTC, merged