feat: Добавлены компоненты If, Switch
quarx-ui/quarx pull request #101
Opened 2022-10-29 23:11 UTC by maximzadorkin

Если кто-то кодил на Vue - видел, что там пишутся template вместо jsx(как правило). Есть там интересные подходы касаемо If. Попробовал к нам в React добавить нечто подобное, чтобы ?:, &&, || перестали быть в нашем react-jsx коде. Мне кажется так повышается читаемость и в целом код становится получше.  Что думаете на счет того, чтобы добавить эти компоненты к нам в дизайн-систему как unstyled components?

2022-10-31 09:46 UTC, aak-lear commented on packages/core/src/unstyled/If/types.ts
> +    condition: boolean;
```suggestion
    condition: boolean | undefined | null;
```

2022-10-31 09:46 UTC, aak-lear commented on packages/core/src/unstyled/If/types.ts
> +    children?: React.ReactText | React.ReactElement | React.ReactElement[];
`ReactNode` не подходит?

2022-10-31 09:46 UTC, aak-lear commented on packages/core/styles/engine/theme/createTheme/types.ts
> +import { BackdropProps, BadgeProps, BaseButtonProps, Breakpoints, ButtonProps, CheckboxProps, CheckboxSelectionProps, CounterProps, CreateBreakpointsArg, CreateElevationArg, CreatePaletteArg, CreateT
это автоматическая генерация?
нарушает длину строки в `eslint`, да и визуально лучше выглядит, если построчный импорт сделать

2022-10-31 09:46 UTC, aak-lear commented on packages/core/src/unstyled/Switch/Case/types.ts
> +export interface CaseProps
`children` не хватает.
Лучше его явно указывать, а не полагаться на `FC`, иначе пользователь библиотеки будет видеть не полный список проспав, если перейдет сюда посмотреть интерфейс

2022-10-31 11:07 UTC, maximzadorkin commented on packages/core/styles/engine/theme/createTheme/types.ts
> +import { BackdropProps, BadgeProps, BaseButtonProps, Breakpoints, ButtonProps, CheckboxProps, CheckboxSelectionProps, CounterProps, CreateBreakpointsArg, CreateElevationArg, CreatePaletteArg, CreateT
Да, автогенерация так работает
Вообще надо подпилить, чтобы она enter ставила

2022-10-31 12:38 UTC, popopolyakov approved these changes

2022-11-01 12:01 UTC, aak-lear requested changes

2022-11-02 05:56 UTC, ISAYwtf approved these changes

2022-11-02 07:16 UTC, aak-lear approved these changes

2022-11-02 12:11 UTC, merged