Добавлен компонент `SystemBasedThemeProvider`, хук `useSystemTheme`, добавлено открытие темы сторибука с системной темой, компонент `Description` в Story
quarx-ui/quarx pull request #114
Opened 2022-11-09 08:20 UTC by popopolyakov

Добавлен компонент `SystemBasedThemeProvider`, хук `useSystemTheme`, добавлено открытие темы сторибука с системной темой, компонент `Description` в Story

2022-11-09 08:50 UTC, ISAYwtf commented on packages/core/src/unstyled/SystemBasedThemeProvider/__tests__/SystemBasedThemeProvider.test.tsx
> +    const themeType = useTheme();
```suggestion
    const theme = useTheme();
```

или

```suggestion
    const themeType = useTheme().palette.type;
```

2022-11-09 08:52 UTC, ISAYwtf commented on packages/core/utils/hooks/useIsomorphicLayoutEffect/useIsomorphicLayoutEffect.ts
> +export const useIsomorphicLayoutEffect = typeof window !== 'undefined' ? useLayoutEffect : useEffect;
то же самое в `useEnhancedEffect`

2022-11-09 11:06 UTC, popopolyakov commented on packages/core/src/unstyled/SystemBasedThemeProvider/SystemBasedThemeProvider.tsx
> +    return <ThemeProvider theme={overwrittenTheme || theme} {...props} />;
Зря вынес overwrittenTheme, изначально как раз предусматривалось использование вместо `Theme.Provider` c возможностью перебить всю логику систем обычным theme

2022-11-14 07:08 UTC, aak-lear requested changes

2022-11-14 07:08 UTC, aak-lear commented on package.json
> +    "storybook-addon-designs": "^6.3.1",
`6.2.1`

2022-12-01 12:54 UTC, merged