fix(OverScreen): Исправлена анимация
quarx-ui/quarx pull request #132
Opened 2022-11-30 14:32 UTC by ISAYwtf

Исправлено:
1. Компонент `Transition` по умолчанию теперь использует длительность `duration.short` (250 ms);
2. При `keepMounted` = `true` компонент перекрывал весь контент на странице оставаясь прозрачным;
3. Размонтирование рутового элемента теперь реализуется компонентом `DelayedMounter`;
4. Анимация свойства `slide` теперь рассчитывается относительно позиции на экране и ширины всего экрана;
5. Удалено свойство `ContentTransitionProps`, вместо него используется `TransitionProps`;
6. `Backdrop` теперь по умолчанию использует свойства из `TransitionProps` для синхронизации анимации, с возможностью перезаписи. Добавлено:
1. Добавлено новое свойство `easingOutIn` для `transition`;

2022-12-05 13:04 UTC, maximzadorkin requested changes

2022-12-05 13:04 UTC, maximzadorkin commented on packages/core/src/system/OverScreen/helpers/getCurrentIndex.ts
> +) => getOverScreens(currentNode, uniqAttr).length - 1;
Для этого точно нужна отдельная функция? В данном случае просто число бы тогда описать константой откуда оно взялось

2022-12-05 14:21 UTC, ISAYwtf commented on packages/core/src/system/OverScreen/stories/OverScreen.story.tsx
> +// import { defineCategory, excludeProp } from '@core/storybook/templateParams';
Да, Сеня сказал, пока сторибук не выкладывать, так как с названием до конца не определились

2022-12-05 14:25 UTC, ISAYwtf commented on packages/core/src/system/OverScreen/helpers/getMapStyles/originPositions.ts
> +const getNegativePos = (offset: number, size: number) => `${(offset + size) * -1}px`;
Мне так показалось более читаемо, но с другой стороны согласен, лишняя операция, исправлю

2022-12-06 05:41 UTC, ISAYwtf commented on packages/core/src/system/OverScreen/helpers/disableBackdrop.ts
> +    if (backdrop) {
Например, `[undefined, {}]`?

2022-12-06 05:46 UTC, ISAYwtf commented on packages/core/src/system/OverScreen/helpers/getCurrentIndex.ts
> +) => getOverScreens(currentNode, uniqAttr).length - 1;
Вообще согласен, просто функциональный подход показался более описательным, но лишние вызовы, наверное, не очень хорошо, исправлю

2022-12-06 13:38 UTC, maximzadorkin commented on packages/core/src/system/OverScreen/helpers/disableBackdrop.ts
> +    if (backdrop) {
почему не просто null?

2022-12-06 14:01 UTC, ISAYwtf commented on packages/core/src/system/OverScreen/helpers/disableBackdrop.ts
> +    if (backdrop) {
Можно и `null` в принципе, просто тогда при использовании добавляются лишние действия. Но если возвращать не массив, а объект то только проверка добавится, исправлю на такой вариант

2022-12-06 14:13 UTC, maximzadorkin approved these changes

2022-12-06 14:19 UTC, merged