feat: Добавлен системный компонент **Stack**
quarx-ui/quarx pull request #164
Opened 2023-01-12 14:39 UTC by aak-lear

Предназначен для позиционирования элементов, расположенных на одной оси с равными отступами

Resolve #163

2023-01-22 19:15 UTC, maximzadorkin requested changes

2023-01-22 19:15 UTC, maximzadorkin commented on packages/core/utils/addCssToElement.ts
> +    let clonedElement = element.props.__EMOTION_TYPE_PLEASE_DO_NOT_USE__ || element.type;
__EMOTION_TYPE_PLEASE_DO_NOT_USE__  Мне кажется тут имеется конфликт 😄

2023-01-22 19:15 UTC, maximzadorkin commented on packages/core/src/system/Stack/Stack.tsx
> +        spacing = '8px',
Не будем css varами такое задавать?

2023-01-22 19:15 UTC, maximzadorkin commented on packages/core/src/system/Stack/styles/types.ts
> +type AlignItems =
В typescript не существует подобного типа? Может покопаться в CSSProperties

2023-01-22 19:15 UTC, maximzadorkin commented on packages/core/src/system/Stack/styles/types.ts
> +     */
Я на проекте переписал везде, чтобы так было:
```
/** Отступ между элементами контейнера
 *
 * @default 8px */
```

2023-01-22 19:15 UTC, maximzadorkin commented on packages/core/src/system/Stack/styles/index.ts
> +            '&:not(:last-child)': {
С last-child нет проблем в emotion?

2023-01-23 07:15 UTC, aak-lear commented on packages/core/src/system/Stack/styles/types.ts
> +     */
Чтобы не было новой строки в начале и в конце?

2023-01-23 07:15 UTC, aak-lear commented on packages/core/src/system/Stack/styles/index.ts
> +            '&:not(:last-child)': {
нет проблем

2023-01-23 07:17 UTC, aak-lear commented on packages/core/utils/addCssToElement.ts
> +    let clonedElement = element.props.__EMOTION_TYPE_PLEASE_DO_NOT_USE__ || element.type;
для клонирования элемента с добавлением `css` они рекомендуют именно так делать)

2023-01-23 09:37 UTC, maximzadorkin commented on packages/core/src/system/Stack/styles/types.ts
> +     */
Да

2023-01-24 09:18 UTC, aak-lear commented on packages/core/src/system/Stack/styles/types.ts
> +type AlignItems =
Вообще есть, но там довольно много лишних свойств. Решил оставить только используемые с флексом, чтобы автодополнение не путало пользователей

2023-01-25 07:34 UTC, maximzadorkin approved these changes

2023-01-25 07:34 UTC, maximzadorkin commented on packages/core/src/system/Stack/styles/index.ts
> +import { cssVar } from '../../../../utils';
Импорт слетел

2023-01-25 10:56 UTC, merged