feature: Переписать storybook на новую файловую архитектуру
quarx-ui/quarx pull request #184
Opened 2023-02-02 02:24 UTC by maximzadorkin

resolve #183

2023-02-02 03:06 UTC, maximzadorkin commented
Если у кого-то имеются идеи, что добавить в ToDo, то пишите в комментах в следующем формате:
```
- [ ] task
```

2023-02-06 11:54 UTC, maximzadorkin commented
- [ ] Badge
- [ ] Button
- [ ] Checkbox
- [ ] Chips
- [ ] Counter
- [ ] Link
- [ ] Loader
- [ ] Modal
- [ ] RadioButton
- [ ] Selections
- [ ] SidePage
- [ ] Switcher
- [ ] Tabs
- [ ] TextField
- [ ] Backdrop
- [ ] ClickAwayListener
- [ ] DelayedMounter
- [ ] FooterBlock
- [ ] HeaderBlock
- [ ] If
- [ ] OverScreen
- [ ] Popup
- [ ] Portal
- [ ] Stack
- [ ] Switch
- [ ] Transition

2023-02-14 07:08 UTC, ISAYwtf commented
Тип коммита можно исправить на `tech` думаю

2023-02-15 11:50 UTC, ISAYwtf commented
Кстати по поводу `.defaultArgs = args`. Это не нужно делать, так как в объекте `export default` мы указываем `args: defaultArgs` и это автоматически распространяется на все остальные стори на этой странице. Поэтому можно второй пункт исправить на "Проверить, что в .story.tsx проставляются `args: defaultArgs` и удалить логику в forEach в конце файла."

2023-04-10 07:58 UTC, ISAYwtf commented on packages/core/src/main/Link/storybook/customComponent/index.tsx
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
```suggestion
/* eslint-disable @typescript-eslint/no-explicit-any */
```

2023-04-10 08:20 UTC, ISAYwtf commented on STORYBOOK.md
Может этот файл положить в папку md? Чтоб правила/рекомендации в одном месте были собраны

2023-04-10 08:23 UTC, ISAYwtf approved these changes

2023-04-10 08:26 UTC, popopolyakov commented on packages/core/src/main/Checkbox/storybook/Checkbox.story.tsx
> +        design: designParams('https://www.figma.com/file/kqled9AjBtDMRhWKovsgYf/3.1%E3%83%BBControls?node-id=8672%3A61110'),
ссылка на старый чекбокс

2023-04-10 08:26 UTC, popopolyakov commented on packages/core/src/main/Counter/storybook/Counter.story.tsx
> +    parameters: { actions: { disable: true } },
может добавим ссылку на фигму в каждый возможный компонент?

2023-04-10 08:26 UTC, popopolyakov commented on packages/core/src/main/TextField/storybook/externalSettings/index.tsx
> +                    {' '}
Понимаю, что это было просто скопировано, но может в шаблонную строку

2023-04-10 08:35 UTC, ISAYwtf commented on packages/core/src/main/Counter/storybook/Counter.story.tsx
> +    parameters: { actions: { disable: true } },
У нас вроде как фигма закрыта для внешних пользователей, поэтому я бы наоборот удалил все ссылки на нее

2023-04-10 10:21 UTC, maximzadorkin commented on packages/core/src/main/Counter/storybook/Counter.story.tsx
> +    parameters: { actions: { disable: true } },
Удалил пока оставшиеся ссылки на дизайн. На дейли можем обсудить этот вопрос подробнее

2023-04-10 10:30 UTC, popopolyakov requested changes

2023-04-10 10:30 UTC, popopolyakov commented on packages/core/src/main/Button/storybook/Button.story.tsx
> +const DEMONSTRATION_ALERT = '<small>Доступно только для демонстрации</small>';
это в других стори тоже используется, надо в общие константы вынести, возможно даже вместе с `<br />`

2023-04-10 10:35 UTC, maximzadorkin commented on packages/core/src/main/Button/storybook/Button.story.tsx
> +const DEMONSTRATION_ALERT = '<small>Доступно только для демонстрации</small>';
ага, увидел в нескольких компонентах, сек, сейчас  константы прокину туда тоже

2023-04-10 10:44 UTC, popopolyakov approved these changes

2023-04-10 14:20 UTC, aak-lear commented on packages/core/src/system/If/storybook/If.story.tsx
Сторибук для `If` специально скрыт?

2023-04-10 14:21 UTC, maximzadorkin commented on STORYBOOK.md
Неактуальную версию смотришь, уже положил утром :)

2023-04-10 14:22 UTC, maximzadorkin commented on packages/core/src/main/Badge/storybook/borderRadius/description.md
> +Свойство `borderRadius` использует все стандартные варианты скругления объекта `borderRadii`:
Можно, в данном pr я над этим не думал, но в целом соглашусь

2023-04-10 14:22 UTC, maximzadorkin commented on packages/core/src/main/Badge/storybook/colors/description.md
> +Цвет (своство `color`) определяет цвет фона или обводки (в зависимости от выбранного `type`) компонента `Badge`,
Честно говоря, в этом pr я не перерабатывал имеющиеся описания, а лишь копировал их :) Заменю здесь

2023-04-10 14:23 UTC, aak-lear reviewed
Общая мысль для всей документации:
Если значения какого-либо параметра опираются на объект из темы, например на `borderRadii` или `palette.colors`, не лучше ли приписывать сразу `theme.`, чтобы точно было понятно, о каких значениях идет речь?

@maximzadorkin с мыслью согласен

@popopolyakov и @ISAYwtf, что думаете?

2023-04-10 14:23 UTC, maximzadorkin commented on packages/core/src/main/Chips/storybook/Chips.story.tsx
> +        leftIconColor: { description: 'Цвет левой иконки' },
Вообще jsdoc не совсем предсказуемо для меня работает, поэтому я обычно указываю напрямую, но тут наверное как кому удобнее?

2023-04-10 14:23 UTC, maximzadorkin commented on packages/core/src/system/If/storybook/If.story.tsx
Да, давно скрыли

2023-04-10 14:45 UTC, ISAYwtf commented
> Общая мысль для всей документации:
> 
> Если значения какого-либо параметра опираются на объект из темы, например на `borderRadii` или `palette.colors`, не лучше ли приписывать сразу `theme.`, чтобы точно было понятно, о каких значениях идет речь?
> 
> 
> 
> @maximzadorkin с мыслью согласен
> 
> 
> 
> @popopolyakov и @ISAYwtf, что думаете?

Согласен, в снекбаре как раз так стал делать

2023-04-10 16:47 UTC, maximzadorkin commented
> Общая мысль для всей документации: Если значения какого-либо параметра опираются на объект из темы, например на `borderRadii` или `palette.colors`, не лучше ли приписывать сразу `theme.`, чтобы точно было понятно, о каких значениях идет речь?
> 
> @maximzadorkin с мыслью согласен
> 
> @popopolyakov и @ISAYwtf, что думаете?

Видимо все согласны, нужно где-то это записать

2023-04-11 06:46 UTC, aak-lear approved these changes
Я вижу ты про `theme.borderRadii` исправил в тех местах, где я suggest оставлял

если не сложно, можешь еще глобальным поиском по md файлам глянуть? там точно были другие случаи, где тоже пишется просто `borderRadii`

2023-04-11 12:13 UTC, maximzadorkin commented
> Я вижу ты про `theme.borderRadii` исправил в тех местах, где я suggest оставлял
> 
> если не сложно, можешь еще глобальным поиском по md файлам глянуть? там точно были другие случаи, где тоже пишется просто `borderRadii`

Нашел таких 5 случаев еще, исправил

2023-04-11 12:31 UTC, merged