feat: Добавлен компонент **Breadcrumbs**
quarx-ui/quarx pull request #194
Opened 2023-02-17 11:04 UTC by maximzadorkin

resolve #117

2023-06-20 14:37 UTC, aak-lear requested changes

2023-06-20 14:37 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/Breadcrumb/Breadcrumb.tsx
> +        maxCrumbLength = 24,
magic number

2023-06-20 14:37 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/Breadcrumb/Breadcrumb.tsx
> +            <a
хорошо бы сделать здесь OverridableComponent

2023-06-20 14:37 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/Breadcrumb/Breadcrumb.tsx
> +    const isPrimitiveValue = typeof children === 'string' || typeof children === 'number';
это можно вынести в helper

2023-06-20 14:37 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/Breadcrumb/styles/index.ts
> +const mapSizeToTypographySize: Record<BreadcrumbSize, 'S' | 'M' | 'L'> = {
теперь `typography` можно достать из `theme`, размеры там совместимы с `QX_SIZE`, и мапа не потребуется

2023-06-20 14:37 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/Breadcrumb/styles/index.ts
> +}), { name: 'QxBreadcrumb' });
если правильно помню, `name` здесь уже можно не указывать. Этот параметр передается в `stylesProps`, которые возвращает `usePropsOverwrites`

2023-06-20 14:37 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/Breadcrumbs.tsx
> +        maxCrumbTextLength = 24,
magic numbers

24 уже даже повторилось)

2023-06-20 14:37 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/DroppedBreadcrumb/DroppedBreadcrumb.tsx
> +        <a
здесь тоже можно сделать OverridableComponent

2023-06-20 14:37 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/styles/constants.ts
пустой файл

2023-06-20 14:37 UTC, aak-lear commented on packages/core/src/system/Collapse/storybook/common.tsx
> -    maxWidth: '100%',
это вроде было нужно для отображения горизонтального `Collapse`

2023-06-20 14:37 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/storybook/collapse/index.tsx
> +    title: 'Сокрытие промежуточных элементов',
```suggestion
    title: 'Скрытие промежуточных элементов',
```
"Сокрытие" как-то по судебному звучит)

2023-06-20 14:37 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/storybook/collapse/index.tsx
> +    title: 'Сокрытие промежуточных элементов',
Там еще в нескольких местах по тексту есть "сокрытие", имхо лучше везде в "скрытие" переименовать

2023-06-20 14:37 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/DroppedBreadcrumb/storybook/BreadcrumbDropdownItem.story.tsx
В сторибуке **DroppedBreadcrumb** можно настраивать множество параметров, но при этом ничего не изменяется. Попробовал прощелкать все параметры кастомизации – результата нет

2023-06-21 10:16 UTC, maximzadorkin commented on packages/core/src/main/Breadcrumbs/Breadcrumb/styles/index.ts
> +}), { name: 'QxBreadcrumb' });
Окей

2023-06-21 10:17 UTC, maximzadorkin commented on packages/core/src/system/Collapse/storybook/common.tsx
> -    maxWidth: '100%',
Я с Сеней обсуждал прежде чем удалить

2023-06-21 10:20 UTC, maximzadorkin commented on packages/core/src/main/Breadcrumbs/DroppedBreadcrumb/storybook/BreadcrumbDropdownItem.story.tsx
Видимо нужно подписать, идея судя по всему непонятна. 


Breadcrumb и DroppedBreadcrumb работают уже как кастомные компоненты даже на уровне QuarX, соответственно DroppedBreadcrumb наследует стилевые оформления (мало ли кому захочется закастомить), при этом по умолчанию он их не реализует, я в коде оставлял комментарий касаемо этого. Для сторибука можно только сделать definegroup 'для реализации интерфейса', что я уже сделал

2023-06-21 10:42 UTC, maximzadorkin commented on packages/core/src/main/Breadcrumbs/Breadcrumbs.tsx
в целом можно еще как вариант функции по утилитам разбросать и стек breadcrumbs как отдельный компонент сделать и будет повеселее

2023-06-21 16:29 UTC, maximzadorkin commented on packages/core/src/main/Breadcrumbs/Breadcrumb/Breadcrumb.tsx
> +        maxCrumbLength = 24,
Это не magic number. В данном случае происходит присвоение к конкретной переменной, как и в следующем случае

2023-06-21 16:51 UTC, maximzadorkin commented on packages/core/src/main/Breadcrumbs/Breadcrumb/styles/index.ts
> +const mapSizeToTypographySize: Record<BreadcrumbSize, 'S' | 'M' | 'L'> = {
получается нужно делать мапу font-weight теперь у нас в коде :(

2023-06-21 17:02 UTC, maximzadorkin commented on packages/core/src/main/Breadcrumbs/Breadcrumb/styles/index.ts
> +const mapSizeToTypographySize: Record<BreadcrumbSize, 'S' | 'M' | 'L'> = {
кстати так удобнее получилось, заменил во всех breadcrumb компонентах

2023-06-21 17:51 UTC, maximzadorkin commented on packages/core/src/main/Breadcrumbs/Breadcrumbs.tsx
Решил сделать 2 хука для навигации и для общих стилевых состояний. Не стал трогать отрисовку, оставил всю ее в самом компоненте

2023-06-22 10:17 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/Breadcrumb/Breadcrumb.tsx
> +            <a
то, что нужно дополнительно обрабатывать – это уже забота пользователя)
наше дело предоставить ему максимальную гибкость. Он ведь может обернуть Breadcrumb в какую-нибудь ссылку от библиотеки с маршрутизацией, обработать пропс `link`, а остальное прокинуть в `<a>`

2023-06-22 10:56 UTC, aak-lear requested changes

2023-06-22 10:56 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/useBreadcrumbsNavigation.ts
а управление стрелками клавиатуры не завезли 😢

2023-06-22 10:56 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/Breadcrumb/Breadcrumb.tsx
> +            <a
> Плюс кто-то может захочет сделать button вместо a 

Вот, кстати, уже кейс для QuarX:
когда хлебные крошки скрыты, то `...` – это должна быть кнопка, а не ссылка. Потому что по своей логике она не ведет на другую страницу, а выполняет действие – открыть список.

И я уже столкнулся с проблемой того, что навелся на это троеточие с клавиатуры, нажал пробел, а список не открывается. Я ожидал, что он откроется, потому что думал, что нажимаю кнопку, ведь это логично – кнопка открывает список)

2023-06-22 10:56 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/storybook/collapse/index.tsx
> +                Предустановка по сокрытию. При соблюдении условия
```suggestion
                Предустановка по скрытию. При соблюдении условия
```

2023-06-22 10:56 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/storybook/collapse/index.tsx
> +                Кастомизация сокрытия. В данном случае со 2 до 6 элементов.
```suggestion
                Кастомизация скрытия. В данном случае со 2 до 6 элементов.
```

2023-06-22 10:57 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/useBreadcrumbsNavigation.ts
желательно добавить его и для списка горизонтальных крошек, стрелками "влево" и "вправо", и для списка скрытых крошек, стрелками "вверх" и "вниз"
`useKeyboardNavigation` в помощь

2023-06-22 11:00 UTC, maximzadorkin commented on packages/core/src/main/Breadcrumbs/Breadcrumb/Breadcrumb.tsx
> +            <a
Если мы снимаем с себя ответственность за обработку подобных сценариев и возлагаем их на пользователя - тогда да, идея хорошая :)

2023-07-04 12:57 UTC, aak-lear commented on packages/core/src/main/Breadcrumbs/Breadcrumb/Breadcrumb.tsx
для дропнутых крошек необходимо добавить вертикальную навигацию с клавиатуры

2023-10-27 19:36 UTC, aak-lear approved these changes

2023-10-27 21:15 UTC, merged