feat: Добавлен компонент **Breadcrumbs**
quarx-ui/quarx pull request #228
Opened 2023-05-26 19:43 UTC by krifoElectron

2023-05-30 09:22 UTC, aak-lear commented on e2e/src/main/Modal/tests/Modal.test.pw.ts-snapshots/scrollBehavior-body/Modal-chromium-darwin.jpeg
@maximzadorkin, я так понимаю это мы обновили отступы в модалке, но не обновили e2e тесты

2023-05-30 09:23 UTC, aak-lear commented on e2e/src/main/Modal/tests/Modal.test.pw.ts-snapshots/scrollBehavior-body/Modal-chromium-darwin.jpeg
нужно будет настроить автоматический запуск e2e тестов в actions 😄

2023-05-30 09:50 UTC, aak-lear requested changes

2023-05-30 09:50 UTC, aak-lear commented on e2e/src/system/Collapse/tests/Collapse.test.pw.ts-snapshots/collapsedSize/5/Collapse-chromium-darwin.jpeg
здесь не полностью закрыт контент, так и задумано?

2023-05-30 09:50 UTC, aak-lear commented on packages/core/src/system/Collapse/styles/index.ts
> +        width: 'fit-content',
возможно это свойство нужно только при сворачивании в горизонтальном направлении, а в вертикальном может негативно повлиять на верстку

2023-05-30 09:50 UTC, aak-lear commented on packages/core/src/system/Collapse/types.ts
> +     * когда он всёрнут
😄 
```suggestion
     * когда он свёрнут
```

2023-05-30 09:50 UTC, aak-lear commented on packages/core/src/system/Collapse/types.ts
> +    transitionProps?: Omit<TransitionProps, Exclude<keyof CollapsePropsWithoutHtml, 'transitionProps'>>;
при передаче пропсов в другой компонент, лучше имя компонента писать с большой буквы, чтобы было понятно, что речь именно о внутреннем компоненте, а не просто похожее название пропса

```suggestion
    TransitionProps?: Omit<TransitionProps, Exclude<keyof CollapsePropsWithoutHtml, 'transitionProps'>>;
```

2023-05-30 09:50 UTC, aak-lear commented on packages/core/src/system/Collapse/types.ts
> +     * @default false */
в коде компонента `timeout` по-умолчанию не `false`

2023-05-30 09:50 UTC, aak-lear commented on packages/core/src/system/Collapse/Collapse.tsx
> +    const isVertical = orientation === 'vertical';
Строковые значения `'vertical'` и `'horizontal'` лучше использовать из констант

они уже есть в проекте:
`packages/core/enums/orientations.ts`

2023-05-30 09:50 UTC, aak-lear commented on packages/core/src/system/Collapse/types.ts
> +export type CollapseOrientation = 'horizontal' | 'vertical'
можно унаследовать от типа `Orientation`

2023-05-30 09:50 UTC, aak-lear commented on packages/core/src/system/Collapse/storybook/Collapse.story.tsx
> +export default {
можно в сторибуке выключить неиспользуемые контролы `open` и `children`

2023-05-30 09:55 UTC, aak-lear requested changes

2023-05-30 09:55 UTC, aak-lear commented on packages/core/src/system/Collapse/Collapse.tsx
> +                styles={{}}
пустой объект?

2023-05-30 10:08 UTC, aak-lear commented on packages/core/src/system/Collapse/styles/constants.ts
> +export const ENTER_ANIMATION_FUNCTION = 'cubic-bezier(.8,.4,.97,.62)';
такая анимация на вход выглядит довольно резко в конце

<img width="270" alt="image" src="https://github.com/quarx-ui/quarx/assets/54769688/5f3a39c7-4cff-4b18-8897-310072548fe0">

Лучше использовать стандартный ease-in-out, и out-in для выхода

<img width="272" alt="image" src="https://github.com/quarx-ui/quarx/assets/54769688/05019b6c-bca7-40e4-aff4-7bee2895f6c6">

Кстати, тайминги для стандартных анимаций тоже есть в `theme.transitions.easing`

2023-05-30 10:32 UTC, maximzadorkin commented on e2e/src/main/Modal/tests/Modal.test.pw.ts-snapshots/scrollBehavior-body/Modal-chromium-darwin.jpeg
ага, не обновил действительно)

2023-05-30 14:00 UTC, maximzadorkin commented on packages/core/src/system/Collapse/types.ts
> +    /** Если true, то элемент развёрнут */
Лучше описывать функционал как существительное.

2023-05-30 14:04 UTC, maximzadorkin commented on packages/core/src/system/Collapse/storybook/Collapse.story.tsx
> +export { SandboxStory } from './sandbox';
Добавить бы разных сторей для показа пропсов в действии

2023-05-30 14:05 UTC, maximzadorkin commented on packages/core/src/system/Collapse/storybook/sandbox/index.tsx
> +export const SandboxStory: Story<CollapseProps> = ({ ...props }) => {
А в чем смысл `{...props}` ? :D

2023-05-30 14:08 UTC, maximzadorkin commented on packages/core/styles/engine/theme/createTheme/types.ts
> +    Collapse: CollapseProps;
Я о том, что у нас компоненты можно создавать при помощи `yarn new`

2023-05-30 14:42 UTC, aak-lear commented on packages/core/src/system/Collapse/Collapse.tsx
> +                    ?? {
`easing ?? ...` предполагает, что либо обе функции переданы, либо вообще не передан объект `easing`

но пропсы поддерживают частичную передачу `{ enter?: ..., exit?: ... }`, а значит пользователь может передать только `enter` или только `exit`. В таком случае одна из функций не сработает, потому что в пропсы будет отправлен объект с одним свойством.

Поэтому нужно что-то такое:
`{
    enter: easing?.enter ?? ENTER_ANIMATION_FUNCTION,
    exit: easing?.exit ?? EXIT_ANIMATION_FUNCTION,
}`

2023-05-30 14:58 UTC, aak-lear commented on packages/core/src/system/Collapse/styles/index.ts
> +        width: 'fit-content',
Ну да, если контент не занимает по ширине всю страницу, то он отображается только в пределах своей собственной ширины. Это может негативно влиять на элементы, которые по-умолчанию рассчитывают занимать всю доступную ширину.

Ниже примеры с Divider:

1) Когда работает `fit-content`
<img width="944" alt="image" src="https://github.com/quarx-ui/quarx/assets/54769688/901df78e-9a5d-4ec3-936b-6e8b3a322f34">

2) Когда отключен `fit-content`
<img width="934" alt="image" src="https://github.com/quarx-ui/quarx/assets/54769688/a76d753f-feaa-4ce4-aa92-832ac0a1da0f">

2023-06-01 11:00 UTC, ISAYwtf commented on packages/core/src/system/Collapse/storybook/Collapse.story.tsx
> +};
Лучше так
```suggestion
} as Meta<CollapseProps>;
```
а сверху type cast убрать

2023-06-01 11:00 UTC, aak-lear requested changes

2023-06-01 11:01 UTC, ISAYwtf commented on packages/core/src/system/Collapse/storybook/Collapse.story.tsx
> +};
Meta из `@storybook/react` импортится

2023-06-01 11:06 UTC, ISAYwtf commented on packages/core/src/system/Collapse/styles/types.ts
> +    /** Горизонтальное ли направления скрытия элемента
```suggestion
    /** Признак горизонтального направления скрытия элемента
```

2023-06-01 11:40 UTC, aak-lear approved these changes

2023-06-01 11:55 UTC, ISAYwtf commented on packages/core/src/system/Collapse/Collapse.tsx
> +                mapStatusToStyles={{
Договорились не выносить? Просто диалог зарезолвен, но не исправлено. Или там на что-то другое было?

2023-06-01 12:00 UTC, maximzadorkin requested changes

2023-06-01 12:00 UTC, maximzadorkin commented on packages/core/src/system/Collapse/types.ts
> +export type CollapseProps = ComponentPropsWithHTML<CollapsePropsWithoutHtml>
не исправлено(

2023-06-01 12:44 UTC, maximzadorkin commented on packages/core/src/system/Collapse/storybook/sandbox/index.tsx
> +                        padding: '10px 20px',
и тут

2023-06-01 12:45 UTC, maximzadorkin commented on packages/core/src/system/Collapse/storybook/collapsedSize/index.tsx
> +import { FlexContainer } from '@core/src/system/DelayedMounter/storybook/components';
вот так лучше не надо. у нас есть компоненты Row и Column для сторибука специально

2023-06-01 13:50 UTC, maximzadorkin approved these changes

2023-06-01 13:50 UTC, maximzadorkin approved these changes

2023-06-01 13:50 UTC, maximzadorkin approved these changes

2023-06-01 13:53 UTC, merged