feat: Добавлен компонент **Alert**
quarx-ui/quarx pull request #234
Opened 2023-06-01 11:24 UTC by ISAYwtf

2023-06-06 10:11 UTC, maximzadorkin requested changes
Если можно апдейт залей отдельным коммитом)

2023-06-06 10:11 UTC, maximzadorkin commented on packages/core/src/main/Alert/storybook/Alert.story.tsx
> +export { Alert } from './sandbox';
SandboxStory))

2023-06-06 10:11 UTC, maximzadorkin commented on packages/core/src/main/Alert/storybook/sandbox/index.tsx
> +    <AlertKit
Некорректно код скорее всего показывается в сторибуке

2023-06-06 10:11 UTC, maximzadorkin commented on packages/core/src/main/Alert/elements/types.ts
> +    type: AlertType;
а почему ты \n не ставишь между комментариями и типом новым?

2023-06-06 10:11 UTC, maximzadorkin commented on packages/core/src/main/Alert/elements/ActionButtons/styles/index.ts
> +    root: {
компонент Stack можно заюзать

2023-06-06 10:11 UTC, maximzadorkin commented on packages/core/src/main/Alert/elements/Body/Body.tsx
> +import { ALERT_TYPE } from '@core/src/main/Alert';
некорректный path

2023-06-06 10:11 UTC, maximzadorkin commented on packages/core/src/main/Alert/elements/Body/styles/index.ts
> +        flexDirection: 'column',
Тож Stack можно юзать, везде не буду писать, чтобы не захламлять

2023-06-06 10:15 UTC, maximzadorkin requested changes

2023-06-06 10:15 UTC, maximzadorkin commented on packages/core/src/system/TimerCircle/TimerCircle.tsx
> +
Знаешь, было бы круто, если бы был хук дефолтный по управлению таймером. А то придется писать самостоятельно, а это не весело, когда тебя надо дефолтно все

2023-06-06 10:15 UTC, maximzadorkin commented on packages/core/src/main/Alert/elements/LeftItem/LeftItem.tsx
> +        case false:
Кастомный нельзя будет пробросить?

2023-06-07 09:19 UTC, ISAYwtf commented on packages/core/styles/engine/theme/hooks/useProps/types.ts
> +    & Permissions
Переносил из времени когда еще не было точки с запятой у нас)) странно что `eslint` не подсветил мне

2023-06-07 09:28 UTC, ISAYwtf commented on packages/core/src/system/TimerCircle/TimerCircle.tsx
> +        return timerValue || timerValue === 0 ? seconds : '';
В принципе это условие вообще можно убрать, лучше так думаю: `seconds ?? ''`

2023-06-07 09:33 UTC, ISAYwtf commented on packages/core/src/main/Alert/storybook/sandbox/index.tsx
> +    <AlertKit
На удивление нормально)

2023-06-07 10:41 UTC, ISAYwtf commented on packages/core/src/main/Alert/elements/Body/Body.tsx
> +import { ALERT_TYPE } from '@core/src/main/Alert';
В каком смысле некорректный? Имеешь в виду, что можно сократить?

2023-06-07 10:42 UTC, ISAYwtf commented on packages/core/src/main/Alert/elements/LeftItem/LeftItem.tsx
> +        case false:
Можно `ReactNode`

2023-06-07 10:44 UTC, ISAYwtf commented on packages/core/src/main/Alert/storybook/sandbox/index.tsx
> +    <AlertKit
Вроде все норм

2023-06-07 10:46 UTC, ISAYwtf commented on packages/core/src/main/Alert/elements/types.ts
> +    type: AlertType;
Не очень понял, вопрос в том, почему я не разделяю типы пустыми строками?

2023-06-07 10:49 UTC, ISAYwtf commented on packages/core/src/main/Alert/index.ts
> +export * from './constants';
Мне кажется это не важно, но чтоб глаза тебе не резало приоритизирую 😄

2023-06-07 10:52 UTC, ISAYwtf commented on packages/core/src/main/Alert/storybook/Alert.story.tsx
> +        size: { },
Забыл сторибук обновить)

2023-06-07 12:50 UTC, ISAYwtf commented on packages/core/src/system/TimerCircle/index.ts
> +export * from './TimerCircle';
В отдельном ПР'е сделаю

2023-06-07 13:34 UTC, ISAYwtf commented on packages/core/src/system/TimerCircle/TimerCircle.tsx
> +
У нас есть хук `useTimer`, который я планирую использовать в снекбаре. Если я правильно понял, о чём ты

2023-06-08 13:22 UTC, maximzadorkin requested changes

2023-06-08 13:22 UTC, maximzadorkin commented on packages/core/src/system/TimerCircle/TimerCircle.tsx
> +
Можно просто дать хук по управлению логикой таймера. Чтобы пользователь мог просто useTimerCircle() сделать и у него сразу выдавал timerValue и setTimerValue, а в хуке имелась setTimeout логика

2023-06-08 13:22 UTC, maximzadorkin commented on packages/core/src/system/Stack/types.ts
> +export type StackChild = ReactChild | ReactNode | false | null;
ReactNode уже включает внутри себя ReactChild

2023-06-08 13:22 UTC, maximzadorkin commented on packages/core/src/main/Alert/elements/types.ts
> +    type: AlertType;
да, ты как раз сделал как я и имел ввиду сейчас)

2023-06-08 15:53 UTC, ISAYwtf commented on packages/core/src/system/TimerCircle/TimerCircle.tsx
> +
У нас есть хук `useTimer`, ты про него?

2023-06-08 15:57 UTC, ISAYwtf commented on packages/core/src/system/Stack/types.ts
> +export type StackChild = ReactChild | ReactNode | false | null;
Да, поэтому придется явно типизировать все `children` в других компонентах как `ReactChild`, что не очень удобно, поэтому добавил более нативный `ReactNode`

2023-06-09 07:09 UTC, ISAYwtf commented
TimerCircle залью отдельным ПР'ом сразу с документацией, так как отдельный компонент все таки

2023-06-13 07:53 UTC, aak-lear commented on packages/core/src/system/Stack/types.ts
> +export type StackChild = ReactChild | ReactNode | false | null;
думаю здесь речь о том, что `ReactChild` уже можно не писать

2023-06-13 08:35 UTC, aak-lear requested changes

2023-06-13 08:35 UTC, aak-lear commented on packages/core/src/main/Alert/Alert.tsx
> +        background = 'main',
желательно для значений `main` и `secondary` тоже завести константы и использовать их, а не обычные строковые значения

2023-06-13 08:35 UTC, aak-lear commented on packages/core/src/main/Alert/Alert.tsx
> +    const actionButtonProps = useMemo(() => ({
```suggestion
    const actionButtonsProps = useMemo(() => ({
```

2023-06-13 08:35 UTC, aak-lear commented on packages/core/styles/engine/theme/hooks/useProps/useProps.ts
> + * - Приоритет при слиянии параметров: defaultProps < props < props.permissions
```suggestion
 * - Приоритет при слиянии параметров: props < props.permissions
```

2023-06-13 08:35 UTC, aak-lear commented on packages/core/styles/engine/theme/hooks/useProps/useProps.ts
> +export function useProps<
Единственное отличие от usePropsOverwrites в том, что он не вызывает тему?
Предлагаю тогда общую логику объединить. Сейчас дублирование происходит

2023-06-13 08:49 UTC, ISAYwtf commented on packages/core/src/main/Alert/Alert.tsx
> +        background = 'main',
Они добавлены, просто забыл применить)

2023-06-13 08:55 UTC, ISAYwtf commented on packages/core/styles/engine/theme/hooks/useProps/useProps.ts
> +export function useProps<
Получается, что так. Изначально я просто не хотел добавлять дополнительные проверки, так как их и так много было из-за стилей. Но сейчас это не актуально же, поэтому объединю

2023-06-13 09:02 UTC, ISAYwtf commented on packages/core/styles/engine/theme/hooks/useProps/useProps.ts
> +export function useProps<
Сейчас объединил, оказалось и доп проверки не нужны... у страха глаза велики)

2023-06-20 13:40 UTC, aak-lear approved these changes

2023-06-28 21:20 UTC, maximzadorkin approved these changes

2023-06-28 21:20 UTC, maximzadorkin commented on packages/core/utils/hooks/useTimer/types.ts
> +    disabled?: boolean;
это же уже есть в useTimer? Может ребейзнуться сразу, чтобы не забыть

2023-06-28 21:20 UTC, maximzadorkin commented on packages/core/src/main/Alert/types.ts
> +import { CloseButtonProps } from '@core/src/main/Alert/elements/CloseButton/types';
Замени на относительные пути лучше ./elements/..., чтобы проще читалось

2023-06-28 21:20 UTC, maximzadorkin commented on packages/core/src/main/Alert/elements/CloseButton/index.ts
> +export * from './types';
Рубрика "докопался"

CloseButton по логике последним должен экспортироваться, так как types используется в CloseButton. Но можешь забить :D

2023-06-28 21:20 UTC, maximzadorkin commented on packages/core/src/main/Alert/elements/Body/styles/index.ts
> +    texts: {},
а зачем?

2023-07-03 06:01 UTC, ISAYwtf commented on packages/core/src/main/Alert/elements/Body/styles/index.ts
> +    texts: {},
Чтобы была возможность прокинуть класс для элемента

2023-07-03 06:07 UTC, ISAYwtf commented on packages/core/utils/hooks/useTimer/types.ts
> +    disabled?: boolean;
Не очень понял, пропс `disabled` появился в этом ПР'е. От чего ребейзиться и что не забыть?😄

2023-07-03 06:19 UTC, merged