feat: Добавлена анимация компоненту  **Accordion** с помощью компонен…
quarx-ui/quarx pull request #235
Opened 2023-06-01 14:14 UTC by krifoElectron

…та **Collapse**

2023-06-01 14:17 UTC, maximzadorkin approved these changes

2023-06-01 14:25 UTC, aak-lear requested changes

2023-06-01 14:25 UTC, aak-lear commented on packages/core/src/main/Accordion/types.ts
> +    /** Свойства используемого компонента Transition */
```suggestion
    /** Свойства используемого компонента Collapse */
```

2023-06-01 14:25 UTC, aak-lear commented on packages/core/src/system/Collapse/Collapse.tsx
> +                    className={clsx(cn('root'), className)}
`className` уже мержится внутри `usePropsOverwrites`.
`cn('root')` содержит его в себе

2023-06-01 15:23 UTC, aak-lear requested changes

2023-06-01 15:23 UTC, aak-lear commented on packages/core/src/system/Collapse/Collapse.tsx
> +    console.log({ className: cn('root') });
```suggestion
```

2023-06-01 15:29 UTC, aak-lear approved these changes

2023-06-01 15:29 UTC, aak-lear commented on packages/core/src/system/Collapse/Collapse.tsx
> +import clsx from 'clsx';
А это используется? Вроде нет)

2023-06-01 15:49 UTC, merged

2023-06-02 08:37 UTC, maximzadorkin commented on packages/core/src/main/Accordion/storybook/Accordion.story.tsx
> +            disableTransition: {},
у тебя false же по default в компоненте