feat: Добавлен компонент **TimerCircle**
quarx-ui/quarx pull request #246
Opened 2023-06-19 07:01 UTC by ISAYwtf

2023-06-19 08:48 UTC, aak-lear requested changes

2023-06-19 08:48 UTC, aak-lear commented on packages/core/utils/hooks/useTimer/types.ts
> +    /** Callback срабатываемый при паузе */
```suggestion
    /** Callback срабатывающий при паузе */
```

2023-06-19 08:48 UTC, aak-lear commented on packages/core/utils/hooks/useTimer/types.ts
> +    /** Callback срабатываемый при первом запуске */
можно еще назвать "вызываемый", если так удобнее будет

2023-06-19 08:48 UTC, aak-lear commented on packages/core/utils/hooks/useTimer/types.ts
> +    /** Callback срабатываемый при окончании */
```suggestion
    /** Callback срабатывающий при окончании */
```

2023-06-19 08:48 UTC, aak-lear commented on packages/core/utils/hooks/useTimer/types.ts
>      interval?: number;
хорошо бы дописать, что всё время в секундах указывается

2023-06-19 08:48 UTC, aak-lear commented on packages/core/utils/hooks/useTimer/types.ts
> +    /** Масштаб интервала
наверное правильнее будет назвать "длительность интервала"
и дополнительно указать, что единицы измерения – милисекунды

2023-06-19 08:48 UTC, aak-lear commented on packages/core/src/system/TimerCircle/styles/index.ts
> +    loaderBackground: { stroke: colors.Black[8] },
Хорошо бы взять нужный цвет из токенов. Иначе возникает сразу 2 проблемы:
1. нет кастомизации
2. в темной теме нет фона у таймера

2023-06-19 08:48 UTC, aak-lear commented on packages/core/src/system/TimerCircle/styles/index.ts
> +    loaderBackground: { stroke: colors.Black[8] },
по второму пункту скрины:

Ожидаемый | Фактический

<img width="48" alt="image" src="https://github.com/quarx-ui/quarx/assets/54769688/0da1bad9-f630-4e8a-bb1d-5b2b8018e2b7"> <img width="48" alt="image" src="https://github.com/quarx-ui/quarx/assets/54769688/22c60e45-e66b-4ccb-a04a-4af011f05c95">

2023-06-19 08:48 UTC, aak-lear commented on packages/core/src/system/TimerCircle/styles/index.ts
> +    loaderBackground: { stroke: colors.Black[8] },
вижу, что компонент опирается на свойство currentColor
в таком случае можно попробовать использовать [color-mix](https://stackoverflow.com/questions/45075231/currentcolor-with-opacity)

поддержка у него так себе, но в целом на современных браузерах работает. Можно использовать его и добавить fallback

2023-06-19 08:48 UTC, aak-lear commented on packages/core/src/system/TimerCircle/storybook/circleSegments/index.tsx
> +export const CircleSegmentsStory: StoryFn<TimerCircleProps> = (props) => (
можно сюда добавить еще один таймер, в котором значение не переполняет круг. А то не сразу понятно, как он работает в обычном режиме

2023-06-19 08:48 UTC, aak-lear commented on packages/core/src/system/TimerCircle/TimerCircle.tsx
> +export const TimerCircle: FC<TimerCircleProps> = (initialProps) => {
не хватает `ref`

2023-06-19 11:09 UTC, ISAYwtf commented on packages/core/utils/hooks/useTimer/types.ts
> +    /** Масштаб интервала
Длительность лично мне не очень понятна, так как есть сам интервал задаваемый в секундах, а это лишь его коэффициент

2023-06-19 11:35 UTC, ISAYwtf commented on packages/core/src/system/TimerCircle/styles/index.ts
> +    loaderBackground: { stroke: colors.Black[8] },
Не очень понял в чем проблема currentColor в данном случае?

2023-06-19 12:19 UTC, ISAYwtf commented on packages/core/utils/hooks/useTimer/types.ts
>      interval?: number;
На самом деле в чем указывается время зависит от `timeScale`, если стоит значение 1000, то в секундах, если 1, то в миллисекундах например)

2023-06-20 10:18 UTC, aak-lear commented on packages/core/src/system/TimerCircle/styles/index.ts
> +    loaderBackground: { stroke: colors.Black[8] },
проблема в том, что в `currentColor` можно задать любой цвет, даже не из токена. И тогда цвета фона и основного цвета круга не будут соответствовать друг другу

2023-06-20 10:31 UTC, aak-lear commented on packages/core/utils/hooks/useTimer/types.ts
> +    /** Масштаб интервала
этот параметр используется как множитель для параметра `interval`.
То есть сам по себе интервал – это какой-то отрезок времени, измеряемый в условных единицах.
И одна условная единица времени – это и есть `timeScale` миллисекунд. В целом название "масштаб" здесь по смыслу подходит, но большинству людей оно будет непонятно.

Поэтому я предлагаю назвать этот параметр как-то ближе к временным измерениям, связать с длительностью

2023-06-20 10:32 UTC, aak-lear commented on packages/core/utils/hooks/useTimer/types.ts
> +    /** Интервал (сек)
Начальное и конечное время действительно измеряется в секундах, насколько я понял.
Но `interval` уже не в секундах, ведь он умножается на `timeScale`

2023-06-20 11:02 UTC, ISAYwtf commented on packages/core/utils/hooks/useTimer/types.ts
> +    /** Масштаб интервала
Да именно так, только он используется как множитель/коэффициент не только для интервала, но и для любых используемых единиц времени (начальное и конечное время, например). Не знаю почему я в названии указал именно интервал). Можно назвать "Продолжительность единицы времени". Слово длительность мне, как я и говорил, не так очевидно.

2023-06-20 11:18 UTC, ISAYwtf commented on packages/core/utils/hooks/useTimer/types.ts
> +    /** Масштаб интервала
Да именно так. Можно назвать "Продолжительность единицы времени". Слово длительность мне, как я и говорил не очень нравится)

2023-06-20 11:23 UTC, ISAYwtf commented on packages/core/utils/hooks/useTimer/types.ts
> +    /** Интервал (сек)
Начальное и конечное время тоже зависят от timeScale. Например, если передать:
startTime: 5000
interval: 1000
timeScale: 1

Здесь уже все измеряется в мс

2023-06-20 12:04 UTC, aak-lear commented on packages/core/utils/hooks/useTimer/types.ts
> +    /** Масштаб интервала
Продолжительность внутренней единицы времени таймера (мс)

получается так?

в остальных параметрах тогда можно убрать приписку (сек)

2023-06-21 08:36 UTC, ISAYwtf commented
У меня на маке браузеры не поддерживают color-mix, поэтому дома закончу с ним работу

2023-06-28 21:08 UTC, maximzadorkin commented on packages/core/utils/hooks/useTimer/types.ts
> +     * @default 1 */
1 - это секунда? или миллисекунда? стоит наверное уточнить

2023-06-28 21:08 UTC, maximzadorkin commented on packages/core/src/system/TimerCircle/TimerCircle.tsx
> +    const { value: innerValue, pause } = useTimer({
TimerProps не нужен?

2023-06-28 21:10 UTC, maximzadorkin commented
Странно, что на таймере 0, а еще происходит движение полосы
<img width="321" alt="image" src="https://github.com/quarx-ui/quarx/assets/57238571/9dd73e5c-cb87-4a54-8031-71cb39084069">

2023-07-03 06:11 UTC, ISAYwtf commented on packages/core/src/system/TimerCircle/TimerCircle.tsx
> +    const { value: innerValue, pause } = useTimer({
Они вынесены в основные пропсы

2023-07-03 06:14 UTC, ISAYwtf commented
> Странно, что на таймере 0, а еще происходит движение полосы <img alt="image" width="321" src="https://user-images.githubusercontent.com/57238571/249615302-9dd73e5c-cb87-4a54-8031-71cb39084069.png">

Согласен, но это происходит из-за того, что анимация построена на обычном transition, в старом ките чтобы решить эту проблему заранее отнимали одну единицу, чтобы анимация была как бы впереди на одну секунду, но это порождало другие проблемы. То есть по сути здесь нужно думать как правильно анимацию строить, может подумать в сторону requestAnimationFrame

2023-07-03 06:15 UTC, ISAYwtf commented on packages/core/utils/hooks/useTimer/types.ts
> +     * @default 1 */
Зависит от того, что передано в `timeScale`

2023-07-10 09:57 UTC, maximzadorkin approved these changes

2023-07-10 10:04 UTC, ISAYwtf commented
> Не знаю будешь решать в этом ПР или в отдельном проблемы с анимацией, но апрув сейчас тогда проставлю. Потом если починишь в этом ПР еще гляну

Поправлю в отдельном

2023-07-10 10:08 UTC, aak-lear commented on packages/core/src/system/TimerCircle/styles/index.ts
> +        transition: 'all 1s linear',
лучше не `all` а конкретные свойства анимировать
иначе могут быть косяки при попытке кастомизировать

2023-07-10 10:10 UTC, aak-lear commented on packages/core/src/system/TimerCircle/styles/index.ts
> +        [`@supports not (stroke: color-mix(in srgb, currentColor 8%, ${palette.background.main}))`]: {
на fallback проверял в браузерах, которые не поддерживают `color-mix`?

2023-07-10 10:10 UTC, aak-lear approved these changes

2023-07-10 10:11 UTC, ISAYwtf commented on packages/core/src/system/TimerCircle/styles/index.ts
> +        [`@supports not (stroke: color-mix(in srgb, currentColor 8%, ${palette.background.main}))`]: {
Да

2023-07-10 10:19 UTC, merged