feat: Добавлен компонент **DatePicker**
quarx-ui/quarx pull request #254
Opened 2023-06-28 14:02 UTC by popopolyakov

2023-07-04 10:14 UTC, aak-lear requested changes
- [ ] Пустой файл: `packages/core/src/main/TextField/stories/TextField.story.tsx`

2023-07-04 10:14 UTC, aak-lear commented on packages/core/src/main/Link/styles/index.ts
> +                '--webkit-tap-highlight-color': 'transparent',
```suggestion
                WebkitTapHighlightColor: 'transparent',
```

2023-07-04 10:14 UTC, aak-lear commented on packages/core/src/main/RadioButton/styles/index.ts
> +                '--webkit-tap-highlight-color': 'transparent',
```suggestion
                WebkitTapHighlightColor: 'transparent',
```

2023-07-04 10:14 UTC, aak-lear commented on packages/core/src/main/Selections/Selection/styles/index.ts
> +            '--webkit-tap-highlight-color': 'transparent',
```suggestion
                WebkitTapHighlightColor: 'transparent',
```

2023-07-04 10:14 UTC, aak-lear commented on packages/core/src/main/TextField/BaseTextField.tsx
> +            <CustomInput
разве кастомный инпут не должен принимать все пропсы, которые компонент передает стандартным инпутам?

2023-07-05 10:27 UTC, popopolyakov commented on packages/core/src/experimental/DatePicker/components/Block/components/DayBlock/DayBlock.tsx
> +        isDayInPeriodLarge } = useDayProperties<D>({
issue #256

2023-07-06 11:50 UTC, ISAYwtf commented on e2e/playwright.config.ts
> +    workers: 3,
Почему 3? Чтоб не перегружать на всякий случай?

2023-07-06 11:56 UTC, ISAYwtf commented on e2e/test-utils/initTest/initTest.ts
> +                    // const waitElementBool = waitElement(page, configTimeout ?? 0);
Коммент. Или нужен?

2023-07-06 12:03 UTC, ISAYwtf commented
Скрины аккордеона поехали

2023-07-06 12:08 UTC, ISAYwtf commented
Почему-то не во всех тестах компонента Link подгрузились шрифты ()

2023-07-06 12:14 UTC, ISAYwtf commented
В SidePage текст во всех скринах почему-то центрирован, в Modal в scrollBehavior-body тоже. Возможно в одном из прошлых ПР'ов Макс что-то сломал, вроде он вносил изменения какие-то

2023-07-06 12:15 UTC, ISAYwtf commented
Табам в скринах тоже плохо

2023-07-06 12:21 UTC, ISAYwtf commented on packages/core/types/isUndefined.ts
> + * Checks if `value` is `undefined`.
У нас везде описание на русском используется, думаю здесь тоже стоит перевести

2023-07-06 12:23 UTC, ISAYwtf commented on packages/core/styles/engine/theme/palette/constants.ts
> +] as const);
Без const разве не работает?

2023-07-06 12:26 UTC, ISAYwtf commented on packages/core/storybook/constants/index.ts
> +export const MINIMAL_VIEWPORTS = {
Файл дублирует содержимое constants на уровне выше

2023-07-06 12:30 UTC, ISAYwtf commented on packages/core/src/system/SystemBasedThemeProvider/SystemBasedThemeProvider.tsx
> +export interface SystemBasedThemeProviderProps extends Partial<ThemeProviderProps> {
Это лучше вынести в отдельный файл и добавить jsdoc

2023-07-06 12:32 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/Wrappers/index.ts
> +export * from './TextFieldDatePicker';
Папку Wrappers с маленькой буквы наверное лучше назвать

2023-07-06 12:33 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/Wrappers/TextFieldDatePicker/constants.ts
> +export const ACTIVE_FIELD_TYPE = valuesAsKeysFromArray(['START', 'END'] as const);
const можно убрать

2023-07-06 12:37 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/Wrappers/TextFieldDatePicker/types.ts
> +    /** Внешняя ошибка конца, которая будет отображаться даже при существующих внутренних ошибках на Period splitted версии */
Не знаю стоит ли специально указывать про приоритетность внешней ошибки над внутренней, это поведение по умолчанию как будто. Но может в принципе лишним не будет

2023-07-06 12:40 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/Wrappers/TextFieldDatePicker/TextFieldDatePicker.tsx
> +        errorByDisallowedPickerDate = 'Выбранная дата вне разрешенного диапазона',
Можно вынести все дефолтные текстовки в константный объект

2023-07-06 12:46 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/Wrappers/TextFieldDatePicker/TextFieldDatePicker.tsx
> +            setErrorText(externalErrorText);
В данном кейсе можно было бы избавиться от обновления внутреннего стейта эффектом. Создать переменную
```ts
const [innerState, setState] = useState(null);

const state = externalState ?? innerState;
```

В таком случае внешнее состояние всегда будет более приоритетно, а при его отсутствии автоматически подставляется внутреннее. Главное в таком случае не использовать externalState как initial значение для useState )

2023-07-06 12:50 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/Wrappers/TextFieldDatePicker/TextFieldDatePicker.tsx
> +                    css={styles.splittedTextFields}
Вообще как вариант здесь можно использовать Stack:

```tsx
<Stack direction="row" spacing="10px">
    ...
</Stack>
```

Но не принуждаю))

2023-07-06 12:54 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/Wrappers/TextFieldDatePicker/utils/format.ts
> +const getFormatMaskDate = (withTime: DatePickerProps['withTime']) => (withTime ? '##.##.#### ##:##' : '##.##.####');
Есть ощущение, что эти маски могут быть использованы где-то еще. Предлагаю вынести в константы

2023-07-06 12:58 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/Wrappers/TextFieldDatePicker/storybook/TextFieldDatePicker.story.tsx
> +        actions: { disable: true },
Это можно не указывать

2023-07-06 13:03 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/Wrappers/TextFieldDatePicker/storybook/TextFieldDatePicker.story.tsx
> +            {selectedPeriod && Object.entries(selectedPeriod)
Для большей красоты `code` в сторибуке я бы вынес перечисление в переменную или компонент отдельный

2023-07-06 13:06 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/Wrappers/TextFieldDatePicker/types.ts
> +    startSplittedPeriodProps?: SplittedTextFieldProps;
Вообще у нас для пропсов, прокидываемых в другие компоненты название с большой буквы указывается, но где-то видел что и с маленькой, возможно в первых компонентах. Надо бы этот вопрос регламентировать если его еще нет conventions

2023-07-06 13:09 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/Wrappers/PopupDatePicker/types.ts
> +    Omit<DatePickerProps<D>, 'classes' | 'styles'>,
омитить лучше в отдельном типе, так же как сделал это выше. Иначе баги могут быть с typescript

2023-07-06 13:10 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/Wrappers/PopupDatePicker/storybook/PopupDatePicker.story.tsx
> +};
Здесь и в TextFieldDatePicker нужно добавить 
```ts
setStoryParams(Sandbox, {
    title: 'Компонент',
})
```

2023-07-06 13:15 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/types.ts
> +export const DATE_PICKER_TIME_TYPES = valuesAsKeysFromArray(['PERIOD', 'PICKER'] as const);
Это лучше вынести в constants

2023-07-06 13:18 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/types.ts
> +export interface PeriodSelectedDates {
Может start и end сделать как отдельный интерфейс, который будут использовать DatePickerAllowedDates и PeriodSelectedDates, чтоб не дублировать

2023-07-06 13:25 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/types.ts
> +    innerStyles?: CommonDatePickerStyles;
Передачу стилей внутренним компонентам мне кажется стоит решать через передачу пропсов для этих компонентов, типа
`DropdownProps`, `DropdownHeaderButtonProps`, `FooterProps`, `HeaderProps` и тд. Там внутри уже styles будет и в целом передачей пропсов компонент будет максимально гибким.

2023-07-06 13:54 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/components/DatePickerRightSection/types.ts
> +    Omit<TimeBadgeProps<D>, 'time' | 'active' | 'styles' | 'classes'>,
В отдельный тип

2023-07-06 14:01 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/utils/styleContstants.ts
> +
Опечатка в названии файла. Использование типографики таким образом помечено как `deprecated`

2023-07-06 14:04 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/components/DayBlock/styles.ts
> +            ':hover': {
Без `&` работает?

2023-07-06 14:05 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/components/DayBlock/types.ts
> +    currentDay: Date;
jsdoc

2023-07-06 14:07 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/types.ts
> +export interface DatePickerStyleParams {
Интерфейсы `StyleParams` должны лежать в `styles/types`, а `styles` в `styles/index`

2023-07-06 14:09 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/components/Dropdown/HeaderButton/types.ts
> +export interface DropdownButtonStyleParam extends Pick<DatePickerStyleParams, 'borderRadius' | 'size'>{
`DropdownButtonStyleParams`

2023-07-06 14:10 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/components/Dropdown/HeaderButton/types.ts
> +export interface DropdownButtonStyleParam extends Pick<DatePickerStyleParams, 'borderRadius' | 'size'>{
`disabled` и выше `opened`

2023-07-06 14:14 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/components/Dropdown/HeaderButton/styles.ts
> +        transition: '0.4s',
Здесь можно использовать

```ts
transition: theme.transitions([...], {
    duration: transition.duration.complex, // либо `0.4s`
})
```

2023-07-06 14:16 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/assets/ChevronDownIcon.svg
> +<path fill-rule="evenodd" clip-rule="evenodd" d="M5.29582 8.29485C5.68635 7.90432 6.31951 7.90432 6.71004 8.29485L11.436 13.0208C11.7027 13.2875 11.836 13.4208 12.0017 13.4208C12.1674 13.4208 12.3007
`fill="currentColor"`

2023-07-06 14:17 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/components/Dropdown/HeaderButton/styles.ts
> +                fill: palette.text.main,
Если в path будет `fill="currentColor"`, то здесь можно изменять `color`, а не `fill`

2023-07-06 14:31 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/components/TimeBadge/types.ts
> +export interface TimeBadgeProps<D extends SelectedDates = PickerSelectedDate> extends
Не хватает дефолтных html-пропсов

2023-07-06 14:32 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/components/TimeBadge/TimeBadge.tsx
> +                onSelectTime(time);
После добавления html-пропсов:
`rest?.onClick?.(e);`

2023-07-06 14:34 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/storybook/sizes-and-display-types/index.tsx
> +SizesAndDisplayTypesStory.storyName = 'Размеры и типы отображения календаря';
```ts
setStoryParams('SizesAndDisplayTypesStory', {
    title: 'Размеры и типы отображения календаря',
    excludeArgs: ['size', 'types'],
    description,
})
```

2023-07-06 14:35 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/storybook/DatePickerBlock.story.tsx
> +// export { FrenchDatePickerStory } from './french-datepicker';
Возможно забыл

2023-07-07 12:35 UTC, popopolyakov commented on packages/core/src/experimental/DatePicker/Wrappers/TextFieldDatePicker/types.ts
> +    startSplittedPeriodProps?: SplittedTextFieldProps;
меня бы это спутало в моменте, пока в типы не зашел, но как решим, я не против

2023-07-07 13:29 UTC, popopolyakov commented on packages/core/src/experimental/DatePicker/components/Block/types.ts
> +    countWeeksInMonth: number;
они внутренние

2023-07-07 13:35 UTC, popopolyakov commented on packages/core/src/experimental/DatePicker/components/Block/types.ts
> +    innerStyles?: CommonDatePickerStyles;
не хочется давать возможность менять пропсы извне, в одном месте изменишь в другом нет и все поедет, календарь работает комплексно и не предполагается использовать отдельно внутренние компоненты

2023-07-07 14:20 UTC, popopolyakov commented on packages/core/src/experimental/DatePicker/components/Block/components/DayBlock/types.ts
> +    currentDay: Date;
это внутренние компоненты

2023-07-10 05:10 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/components/DayBlock/types.ts
> +    currentDay: Date;
Если у внешнего пользователя не должно быть доступа к этим пропсам, то стоит убрать их из интерфейса `ComponentsProps` в `createTheme/types`

2023-07-10 05:29 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/types.ts
> +    innerStyles?: CommonDatePickerStyles;
Спорный момент, но давай оставим как есть. Если понадобится в будущем успеем доработать

2023-07-10 05:43 UTC, ISAYwtf commented
Мне не очень нравится именование компонентов, в том смысле, что я хочу использовать `DatePicker`, но такого компонента нет, есть `TextFieldDatePicker`, `DatePickerBlock` и `PopupDatePicker`. Я +- понимаю логику именования, но она не очень интуитивно понятная. Во-первых, предлагаю `DatePickerBlock` переименовать в `DatePicker` так как это основной "системообразующий" элемент, к тому же компонент в `usePropsOverwrites` так и назван. И, во-вторых, `TextFieldDatePicker` переименовать в `DatePickerSelect`, здесь уже больше субъективности наверное, TextFieldDatePicker слишком длинное название и не до конца понятно о каком текстфилде идет речь, ведь `DateField` уже есть, а `DatePickerSelect` (TextField + DatePicker) будем похож на сам `Select` (TextField + Dropdown).

2023-07-10 06:04 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/DatePickerBlock.tsx
> +    const { props, cn, styleProps } = usePropsOverwrites('DatePicker', initialProps);
`DatePickerBlock`

2023-07-10 08:56 UTC, popopolyakov commented on e2e/playwright.config.ts
> +    workers: 3,
да

2023-07-11 05:59 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/components/DayBlock/styles/index.ts
> +                ':hover': {
Здесь еще `&` забыл

2023-07-11 06:02 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/components/Dropdown/HeaderButton/types.ts
> +export interface DropdownButtonStyleParam extends Pick<DatePickerStyleParams, 'borderRadius' | 'size'>{
Забыл переименовать интерфейс

2023-07-11 06:03 UTC, ISAYwtf commented on packages/core/src/experimental/DatePicker/components/Block/components/Dropdown/HeaderButton/types.ts
> +    isOpen: boolean;
Этот тип из DropdownStyleParams уже есть

2023-07-11 06:06 UTC, ISAYwtf approved these changes

2023-07-11 07:01 UTC, aak-lear approved these changes

2023-07-11 07:02 UTC, popopolyakov commented
Спасибо всем причастным!

2023-07-11 07:03 UTC, merged