feat(TextField): #20 - Добавить компонент TextField
quarx-ui/quarx pull request #46
Opened 2022-07-25 12:56 UTC by ISAYwtf

2022-07-26 07:08 UTC, aak-lear commented on packages/core/src/TextField/MaskedTextField.tsx
> +import InputMask, { Props } from 'react-input-mask';
Может мы не будем тащить внутрь дополнительные библиотеки, а просто дадим возможность интегрировать наше текстовое поле с ними? По сути здесь просто обёртка над `react-input-mask`. Во многих ситуациях вместо неё лучше использовать `react-number-format`, он даже более популярный на npm trends.

Получается нужно с таким подходом нужно делать обертку и над ним тоже)
Предлагаю просто дать какой-то несложный способ интеграции и описать его в `storybook`

2022-07-26 07:11 UTC, aak-lear commented on package.json
> +    "react-input-mask": "^2.0.4"
вроде это должно быть в `core/package.json`

2022-07-26 07:25 UTC, ISAYwtf commented on packages/core/src/TextField/MaskedTextField.tsx
> +import InputMask, { Props } from 'react-input-mask';
Да я так и хочу сделать, просто переносил из старого кита и не удалил еще)

2022-07-26 08:51 UTC, aak-lear commented on packages/core/src/TextField/styles/types.ts
> +    clearIconVisibleOn: TextFieldClearIconVisibleOn,
как-то очень много значений 😄 
мне кажется реально нужными будут только 3:
- always – отображается всегда, если текст введен
- interact – отображается при наведении или фокусе на поле
- none – не отображается совсем (это вместо доп. параметра `disableClearIcon`)

@IgorAraslanov, что думаешь?

2022-07-26 08:51 UTC, aak-lear commented on packages/core/src/TextField/styles/index.ts
> +                0 0 0 4px ${palette.colors.danger.alpha.min}`,
тень повторяется несколько раз, можно вынести в константу, а цвета назначить через css-vars:
```ts
const borderShadowColor = '--border-shadow-color';
const outerShadowColor = '--outer-shadow-color';

const shadow = `inset 0 0 0 2px var(${borderShadowColor}), 0 0 0 4px var(${outerShadowColor})`
```

И затем просто назначать тень в виде константы, при необходимости переопределять цвета. В [Link](https://github.com/quarx-ui/quarx/blob/main/packages/core/src/Link/styles/index.ts) есть пример

2022-07-26 08:51 UTC, aak-lear commented on packages/core/src/TextField/styles/index.ts
> +            },
Здесь не обязательно отдельно переопределять `hover`, достаточно просто поднять специфичность

```suggestion
            disabled && {
                '&&': {
                    backgroundColor: palette.disabled.bg,
                    color: palette.text.secondary,
                    boxShadow: 'none',
                    cursor: 'not-allowed',
                }
            },
```

2022-07-26 09:25 UTC, ISAYwtf commented on packages/core/src/TextField/styles/types.ts
> +    clearIconVisibleOn: TextFieldClearIconVisibleOn,
С учетом опенсорса я бы делал компоненты гибче, особенно такие пропсы, которые довольно сложно переопределить извне. С другой стороны можно и так, если когда-то запрос на добавление появится добавим)

2022-07-26 09:32 UTC, aak-lear commented on packages/core/src/TextField/styles/types.ts
> +    clearIconVisibleOn: TextFieldClearIconVisibleOn,
мне кажется в данном случае наличие большого количества параметров наоборот может ввести пользователя в заблуждение)

2022-07-26 09:51 UTC, IgorAraslanov commented on packages/core/src/TextField/styles/types.ts
> +    clearIconVisibleOn: TextFieldClearIconVisibleOn,
Думаю, что Арсений прав. Вполне лаконично

2022-07-26 10:00 UTC, aak-lear commented on packages/core/src/TextField/styles/types.ts
> +    clearIconVisibleOn: TextFieldClearIconVisibleOn,
значение по-умолчанию можно поставить `interact `

2022-07-26 10:33 UTC, ISAYwtf commented on packages/core/src/TextField/styles/types.ts
> +    clearIconVisibleOn: TextFieldClearIconVisibleOn,
> мне кажется в данном случае наличие большого количества параметров наоборот может ввести пользователя в заблуждение)

Тут я бы поспорил)

2022-07-28 05:42 UTC, ISAYwtf commented on packages/core/src/TextField/styles/index.ts
> +        wrapper: [
Да, думаю можно назвать `field`

2022-07-28 12:57 UTC, aak-lear commented
Нужно коммит в прошедшем времени написать

2022-07-29 09:12 UTC, aak-lear commented on packages/core/src/TextField/stories/TextField.story.tsx
> +export const VisibilityOfClearIcon: Story<TextFieldProps> = (props) => DisplayVariants({
Думаю здесь стоит добавить начальное значение `value`, чтобы текст сразу был введен – тогда не придётся в каждое поле руками что-то вводить, чтобы увидеть разницу
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/54769688/181726530-c5e570dd-37a8-4739-8c39-984ce6056ff9.png">

2022-07-29 09:15 UTC, aak-lear commented on packages/core/src/TextField/stories/TextField.story.tsx
> +export const Overflow: Story<TextFieldProps> = (props) => DisplayVariants({
Здесь хорошо бы уменьшить значение `maxLength` хотя бы до 10, а то много символов приходится вводить, чтобы посмотреть разницу

2022-07-29 09:16 UTC, aak-lear commented on packages/core/src/TextField/stories/TextField.story.tsx
> +export const Helpers: Story<StoryTextFieldProps> = (props) => (
Ну и здесь наверное тоже можно какой-то изначальный текст добавить. Потому что 2 верхних варианта выглядят одинаково, пока писать не начнешь:
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/54769688/181727309-4834c6d9-8472-4d86-9ed1-f0c3d6ca23b1.png">

2022-07-29 09:23 UTC, aak-lear commented on packages/core/src/TextField/styles/index.ts
> +        label: [
Вес шрифта в `label` при `size=small` не соответствует макетам
![image](https://user-images.githubusercontent.com/54769688/181728476-bc03ff41-12f0-4c3a-a34a-253171bc648c.png)
![image](https://user-images.githubusercontent.com/54769688/181728586-9f8491b0-6d19-43b6-b633-a4549b2c2f3e.png)

2022-07-29 09:29 UTC, aak-lear commented on packages/core/src/TextField/stories/TextField.story.tsx
> +export const VisibilityOfClearIcon: Story<TextFieldProps> = (props) => DisplayVariants({
Ещё хорошо бы добавить Story, в которой показать пример интеграции с `react-input-mask` и `react-number-format`

2022-07-29 09:29 UTC, aak-lear commented
Ещё хорошо бы добавить Story, в которой показать пример интеграции с `eact-input-mask` и `react-number-format`

2022-08-01 06:55 UTC, SSPopov requested changes

2022-08-01 06:55 UTC, SSPopov commented on packages/core/src/TextField/TextField.tsx
> +    const ERRORS = {
Нужна возможность менять эти тексты через пропсы

2022-08-01 07:48 UTC, ISAYwtf commented on packages/core/src/TextField/TextField.tsx
> +    const ERRORS = {
Я думаю, что встроенными ошибками вообще никто не воспользуется, учитывая что обычно их передают вместе с валидацией в errorText) но согласен, что возможность стоит добавить

2022-08-01 08:45 UTC, aak-lear approved these changes

2022-08-01 14:33 UTC, SSPopov approved these changes

2022-08-02 12:34 UTC, aak-lear approved these changes

2022-08-02 15:36 UTC, merged