feat: #45 - Добавлен компонент **Counter**
quarx-ui/quarx pull request #64
Opened 2022-08-15 12:07 UTC by ISAYwtf

2022-08-16 06:46 UTC, aak-lear requested changes

2022-08-16 06:46 UTC, aak-lear commented on packages/core/src/Badge/styles/types.ts
> +export type BadgeType = CounterType;
У `Badge` свои типы, они не совпадают с `Color`. В макетах это набор `contained`, `ghosted` и `outlined`

2022-08-17 10:48 UTC, ISAYwtf commented
В макетах в объекте `BorderRadii` есть вариант max, где 100% скругление, нужно добавить его в коде и использовать по умолчанию в `Badge`

2022-08-25 08:43 UTC, IgorAraslanov commented
В Badge надо поправить, то что исправили в дизайне:

- поменяли на `border: 1px`
- поменяли цвет для `ghost` поменял на токен /Surface

2022-08-25 08:45 UTC, aak-lear commented
> В Badge надо поправить, то что исправили в дизайне:
> 
> * поменяли на `border: 1px`
> * поменяли цвет для `ghost` поменял на токен /Surface

- [ ] border: 1px
- [ ] цвет для `ghost` – `surface`

2022-09-07 07:01 UTC, aak-lear approved these changes

2022-09-07 07:01 UTC, merged