feat: Добавлен компонент **DatePicker**
quarx-ui/quarx pull request #77
Opened 2022-09-27 08:38 UTC by popopolyakov

- [ ]  Правки дизайна

2022-09-27 11:18 UTC, maximzadorkin commented
Тесты не прошли

2022-09-27 13:02 UTC, ISAYwtf commented on e2e/README.md
> +> Для обнолвения тестов нужно добавить ` --update-snapshots`
```suggestion
> Для обновления тестов нужно добавить ` --update-snapshots` или `-u`
```

2022-09-27 13:28 UTC, ISAYwtf commented on packages/core/src/DatePicker/Block/__tests__/DatePicker.test.tsx
> +// const TestableDatePeriod: FC = () => {
//

2022-09-27 13:28 UTC, ISAYwtf commented on e2e/src/DatePicker/DatePicker.test.pw.ts
> +        // type: [DATE_PICKER_TIME_TYPES.PERIOD, DATE_PICKER_TIME_TYPES.PICKER],
//

2022-10-12 11:18 UTC, aak-lear commented
При выходе курсора за пределы компонента, состояние наведения продолжает отображаться на дне календаря, который последним был выбран курсором

<img width="307" alt="Снимок экрана 2022-10-12 в 14 17 36" src="https://user-images.githubusercontent.com/54769688/195329256-25bc4b9b-2f3a-414d-b950-26d2849bb287.png">

2022-10-12 11:23 UTC, aak-lear requested changes
Написал про зависание ховера. Также нужна возможность ограничить диапазон дат для выбора. Грубо говоря, добавить `minDate` и `maxDate`

2022-10-12 12:02 UTC, popopolyakov commented
> Написал про зависание ховера. Также нужна возможность ограничить диапазон дат для выбора. Грубо говоря, добавить `minDate` и `maxDate`

trustedDates по сути этим должны заниматься, протестирую их снова, вдруг что

2022-10-13 08:53 UTC, aak-lear commented
Месяца в темной теме явно грустят)

<img width="370" alt="image" src="https://user-images.githubusercontent.com/54769688/195550378-49e9f0c8-cbd9-4041-a662-46c32ead434b.png">

2023-04-14 15:03 UTC, maximzadorkin requested changes

2023-04-14 15:03 UTC, maximzadorkin commented on packages/core/src/main/DatePicker/Block/components/OffsetDayBlock/styles.ts
> +            && !isEqualDays && !isWeekdayName && (isHoveredPeriod ? {
вот это бы тоже как-то по константам разнести, а то с трудом читается

2023-04-14 15:03 UTC, maximzadorkin commented on packages/core/src/main/DatePicker/Block/stories/DatePickerBlock.story.tsx
> +            // type: {
comment

2023-04-14 15:03 UTC, maximzadorkin commented on packages/core/src/main/DatePicker/Block/stories/DatePickerBlock.story.tsx
> +export const Sandbox: Story<StoryType> = ({ ...props }) => {
еще не переписывал на новую структуру сторибука?

2023-04-14 15:03 UTC, maximzadorkin commented on packages/core/src/main/DatePicker/Block/utils/styleUtils.ts
> +    const svg = `url("data:image/svg+xml;utf8,<svg width='${width - 1}px' height='${height}px' viewBox='0 0 ${width - 1} ${height}' fill='none' xmlns='http://www.w3.org/2000/svg'><path d='M0 0 H12' s
может в компонент аккуратненько?

2023-04-14 15:03 UTC, maximzadorkin commented on packages/core/src/main/DatePicker/Block/utils/timeUtils.ts
> +// export const mapTypeToMask = (type : DatePickerTimeTypes): string => {
comment

2023-04-14 15:03 UTC, maximzadorkin commented on packages/core/src/main/DatePicker/Wrappers/PopupDatePicker/PopupDatePicker.tsx
> +    // const { open, onClickAway, anchor, popupProps: { disablePortal = false, ...popupProps }, ...datePickerProps } = props;
задел на будущее наверно?

2023-04-14 16:08 UTC, popopolyakov commented
Это синк с другим компом

2023-04-14 16:08 UTC, closed without merging