feat: #70 - Добавлен компонент `Modal`
quarx-ui/quarx pull request #83
Opened 2022-09-30 09:15 UTC by ISAYwtf

2022-10-04 08:47 UTC, aak-lear requested changes

2022-10-04 08:47 UTC, aak-lear commented on packages/core/src/styled/Modal/Modal.tsx
> +    useLayoutEffect(() => {
`useLayoutEffect` может не работать с SSR. Лучше использовать `useEnhancedEffect`

2022-10-04 08:47 UTC, aak-lear commented on packages/core/utils/hooks/useModalProps/useModalProps.ts
> +    useLayoutEffect(() => {
useEnhancedEffect

2022-10-04 08:47 UTC, aak-lear commented on packages/core/src/styled/Modal/stories/Modal.story.tsx
> +export const BorderRadii: Story<ModalProps> = (props) => DisplayVariants({
Не хватает возможности настроить круглые кнопки внутри модалки. Кажется такая потребность может возникнуть

2022-10-04 13:56 UTC, ISAYwtf commented on packages/core/src/styled/Modal/stories/Modal.story.tsx
> +export const BorderRadii: Story<ModalProps> = (props) => DisplayVariants({
Кнопки в подвале или кнопку закрытия? Вообще и там и там есть такая возможность, например, для кнопки закрытия есть пропс `CloseButtonProps`, а для подвальных кнопок при их передаче можно указать `borderRadius`. Или имеется в виду, что для упрощения нужен один пропс, который изменит скругления для кнопок внутри?

2022-10-17 12:39 UTC, IgorAraslanov requested changes
Всё ок, только нужно скругления поправить

2022-10-20 12:39 UTC, IgorAraslanov approved these changes

2022-10-20 12:39 UTC, IgorAraslanov commented
Единственное, что не хватает, так это примера как внутрь разный контент пихать. Например табы или формы

2022-10-24 11:14 UTC, merged