feat: Добавлен компонент Chips
quarx-ui/quarx pull request #92
Opened 2022-10-12 13:49 UTC by maximzadorkin

resolve #22

2022-10-13 07:24 UTC, ISAYwtf commented
Думаю есть смысл указать в названии коммита номер задачи

2022-10-13 07:24 UTC, ISAYwtf requested changes

2022-10-13 07:24 UTC, ISAYwtf commented on packages/core/src/styled/Chips/Chips.tsx
> +                    {(rightIcon && RightIcon) ? <RightIcon /> : null}
Если есть возможность, что `RightIcon = false` при `rightIcon = true`, то стоит это условие поднять выше, чтоб лишний контейнер не создался при пустом значении, тем более `rightIcon` там уже проверяется

2022-10-13 07:24 UTC, ISAYwtf commented on packages/core/src/styled/Chips/__tests__/Chips.test.tsx
> +describe('Chips snapshots', () => {
Этот блок можно заменить на `testStyleParams`, в других компонентах есть примеры использования

2022-10-13 07:24 UTC, ISAYwtf commented on packages/core/src/styled/Chips/styles/types.ts
> +export type ChipsSize = PickQxSize<'small' | 'base'>;
Думаю `base` лучше заменить на `medium` для стандартизации

2022-10-13 07:24 UTC, ISAYwtf commented on packages/core/src/styled/Chips/styles/types.ts
> +    variant?: ChipsVariant;
```suggestion
    variant: ChipsVariant;
```

2022-10-13 07:24 UTC, ISAYwtf commented on packages/core/src/styled/Chips/styles/index.ts
> +            boxShadow: `0px 0px 0px 3px ${palette.border.focus.dark}, ${elevations.medium}`,
здесь и ниже
```suggestion
            boxShadow: `inset 0px 0px 0px 3px ${palette.border.focus.dark}, ${elevations.medium}`,
```

А вообще предлагаю обводку фокуса теперь создавать иначе. В `Switcher`, `RadioButton` и `Button` (если обновишь `main`-ветку) есть примеры использования `baseFocusStyles` и `stylesWithFocus`.

2022-10-13 11:21 UTC, aak-lear commented on packages/core/src/styled/Chips/styles/types.ts
> +    rightIcon: boolean,
> Про собственную иконку информация от Игоря?

Да, он вроде говорил, что там можно другие иконки поставить. Если правильно помню, он показывал кейс, где чипс может открывать Select и тогда справа будет иконка ChevronDown

2022-10-13 11:26 UTC, aak-lear commented on packages/core/src/styled/Chips/styles/types.ts
> +    variant?: ChipsVariant;
В `...StyleParams` желательно указывать все параметры обязательными, а дефолтное значение в коде компонента проставлять. Это нужно для того, чтобы `useStyles` всегда требовал все параметры, и эти же параметры проставляются в БЭМ-классы компонента. Это важно для возможности кастомизации CSS по отдельному параметру.

2022-10-13 12:08 UTC, maximzadorkin commented on packages/core/src/styled/Chips/styles/types.ts
> +    rightIcon: boolean,
Окей

2022-10-13 12:15 UTC, aak-lear requested changes

2022-10-13 12:15 UTC, aak-lear commented on packages/core/src/styled/Chips/Chips.tsx
> +                    className={cn('leftIcon', params)}
`params` лучше передавать в классы рута, иначе могут быть логические несостыковки.

```suggestion
                    className={cn('leftIcon')}
```

2022-10-13 12:15 UTC, aak-lear commented on packages/core/src/styled/Chips/Chips.tsx
> +                    className={cn('rightIcon', params)}
```suggestion
                    className={cn('rightIcon')}
```

2022-10-13 12:20 UTC, maximzadorkin commented on packages/core/src/styled/Chips/Chips.tsx
> +                    className={cn('leftIcon', params)}
уже был такой коммент, исправлено

2022-10-13 12:21 UTC, maximzadorkin commented on packages/core/src/styled/Chips/Chips.tsx
> +                    className={cn('rightIcon', params)}
уже был такой коммент, исправлено

2022-10-18 07:47 UTC, aak-lear requested changes
Надо бы текст отформатировать, трудно читается

<img width="374" alt="image" src="https://user-images.githubusercontent.com/54769688/196368723-0121a94a-9bbb-48f8-8bf9-60575f050be2.png">

2022-10-18 07:47 UTC, aak-lear commented on packages/core/src/styled/Chips/Chips.tsx
> +const mapRightIconVariant = {
Лучше `variantToRightIcon` либо `mapVariantToRightIcon`

2022-10-18 07:47 UTC, aak-lear commented on packages/core/src/styled/Chips/styles/types.ts
> +export interface ChipsStyleParams {
не хватает описания `@default` значений

2022-10-18 07:47 UTC, aak-lear commented on packages/core/src/styled/Chips/styles/types.ts
> +    existsLeftIcon: boolean,
здесь вроде правильнее `exists` писать в конце

2022-10-20 12:10 UTC, IgorAraslanov requested changes
Активный чипс для фильтра должен быть всегда с иконкой галочки. С возможностью эту иконку поменять на любую другую.

[Пример собрал в фигме](https://www.figma.com/file/i6CnJSetih3Jnw9RtIOnNP/Controls?node-id=22731%3A243096)

2022-10-23 17:35 UTC, maximzadorkin commented
> 

исправлено

2022-10-31 08:13 UTC, aak-lear commented on packages/core/src/styled/Chips/styles/types.ts
> +    animationDuration?: number;
Думаю нам нужно такие вещи, как длительность анимаций, стандартизировать для всех компонентов.
Иначе будет какая-то солянка, где в одних компонентах это можно настраивать, а в других нельзя

2022-10-31 11:10 UTC, maximzadorkin commented on packages/core/src/styled/Chips/styles/types.ts
> +    animationDuration?: number;
Да, можно подумать над этим

2022-10-31 12:52 UTC, maximzadorkin commented
В описании/сторибуке изменить enum на строчные значения

2022-10-31 12:53 UTC, maximzadorkin commented
Убрать animationDuration как пропс до момента, пока не будет составлена глобальная концепция передачи анимационных свойств

2022-11-02 05:36 UTC, ISAYwtf commented on packages/core/src/styled/Chips/stories/Chips.story.tsx
> +        cssLeftIconColor: '#21A038',
`cssVars` нужен, чтобы переименовывать ключи `css`-переменных, а не значения, то есть типа такого:
```ts
cssVars: {
   cssLeftIconColor: '--custom-css-var',
}
```
а изменение значений происходит уже в `styles`:
```ts
styles: (theme, props, { cssLeftIconColor }) => ({
   root: { // или любой другой класс, в котором присваиваются значения для переменной
      [cssLeftIconColor]: '#21A038',
   }
})
```

по поводу необходимости текущей реализации cssVars склоняюсь к тому, что такой механизм мало кому будет полезен, добавлял его больше из интереса ("а вдруг"), чем из практической пользы.

Поэтому предлагаю изменить это поведение на то, которое скорее всего более ожидаемо, то есть изменять значения, а не ключи. Займусь этим в скором времени, а пока стоит убрать отсюда эту строку.

2022-11-02 05:41 UTC, ISAYwtf approved these changes

2022-11-03 15:29 UTC, maximzadorkin commented
Ready to merge)

2022-11-14 07:17 UTC, IgorAraslanov approved these changes

2022-11-14 07:33 UTC, merged